# 用户配置文件
userconfig:
  # 吾爱破解账号cookie
  cookie: cookie
  # 吾爱破解账号formhash
  formhash: formhash
  # 随机选择自动回帖内容
  message-list:
    - 感谢楼主分享！！
    - 可以可以，多谢分享
    - 谢谢分享，用了一下，感觉不错
    - 拿走了，谢谢楼主，好人一生平安
    - 楼主好人，支持一下
    - 非常感谢楼主的分享
    - 这个绝对要支持!!
    - 谢谢楼主分享，下来看看